title: "Александр Черменин"
description: "Data Engineer, разработчик"
email: alex@chermenin.ru
baseurl: ""
url: "https://chermenin.ru"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

sass:
  style: compressed

include:
  - assets/fonts/

collections:
  races:
    output: true
    permalink: /races/:name/

defaults:
  - scope:
      path: "_races"
    values:
      title: "Результаты заездов {date}"
