# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alex::chermenin
email: alex@chermenin.ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chermenin.ru" # the base hostname & protocol for your site
twitter_username: alex_chermenin
github_username:  chermenin

# Build settings
markdown: kramdown

tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: :pretty.html

collections:
  tags:
    output: true
    permalink: /tags/:path/
